# Generated by Django 3.0 on 2021-12-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setups', '0001_initial'),
        ('feecategories', '0001_initial'),
        ('termdates', '0001_initial'),
        ('years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('structure_code', models.AutoField(primary_key=True, serialize=False)),
                ('structure_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feecategories.FeeCategories')),
                ('structure_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='termdates.TermDates')),
                ('structure_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='years.Years')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructureDetails',
            fields=[
                ('structuredetail_code', models.AutoField(primary_key=True, serialize=False)),
                ('structuredetail_ammount', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('structuredetail_Standardcharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.StandardCharges')),
                ('structuredetail_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feesetup.FeeStructure')),
            ],
        ),
    ]
