# Generated by Django 3.0 on 2021-12-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feesetup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructuredetails',
            name='structuredetail_Standardcharge',
        ),
        migrations.RemoveField(
            model_name='feestructuredetails',
            name='structuredetail_structure',
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
        migrations.DeleteModel(
            name='FeeStructureDetails',
        ),
    ]
