"""
Django settings for schoolsys project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import os

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ls3*5$kwz$)_a!n@8h3zqt#aqq3#$s_ig)-+43sw_gio9=vab9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'students.apps.StudentsConfig',
    'setups.apps.SetupsConfig',
    'setups.academics.apps.AcademicsConfig',
    'staff.apps.StaffConfig',
    'staff.teachers.apps.TeachersConfig',
    'setups.academics.classes.apps.ClassesConfig',
    # 'setups.academics.dorms.apps.DormsConfig',
    'setups.academics.departments.apps.DepartmentsConfig',
    'setups.academics.subjects.apps.SubjectsConfig',
    # 'setups.academics.campuses.apps.CampusesConfig',
    'setups.academics.gradesgrid.apps.GradesGridConfig',
    'setups.academics.termdates.apps.TermdatesConfig',
    'setups.academics.mastersetups.apps.MasterSetupsConfig',
    'setups.academics.hmcomments.apps.HmcommentsConfig',
    'setups.academics.subjectgroups.apps.SubjectGroupsConfig',

    'setups.system.parameters.apps.ParametersConfig',
    'setups.system.templates.apps.TemplatesConfig',
    'setups.system.organisation.apps.OrganisationConfig',

    'setups.accounts.accountmaster.apps.AccountMasterConfig',
    'setups.accounts.accountmapping.apps.AccountMappingConfig',

    'studentmanager.apps.StudentmanagerConfig',
    'studentmanager.studentsubjects.apps.StudentsubjectsConfig',

    'studentmanager.parents.apps.ParentsConfig',
    'studentmanager.parents.proffessions.apps.ProffessionsConfig',
    'studentmanager.student.apps.StudentConfig',
    'setups.academics.documents.apps.DocumentsConfig',
    'setups.academics.documents.studentdocuments.apps.StudentdocumentsConfig',
    'setups.academics.campuses.apps.CampusesConfig',
    'setups.academics.denominations.apps.DenominationsConfig',
    'setups.academics.dorms.apps.DormsConfig',
    'setups.academics.sources.apps.SourcesConfig',
    'setups.academics.healthconditions.apps.HealthconditionsConfig',
    'setups.academics.studentstatus.apps.StudentstatusConfig',
    'setups.academics.years.apps.YearsConfig',
    'feemanager.apps.FeemanagerConfig',
    'feemanager.feesetup.apps.FeesetupConfig',
    'feemanager.feesetup.feecategories.apps.FeecategoriesConfig',
    'localities.apps.StudentsConfig',
    'setups.academics.responsibilities.apps.ResponsibilitiesConfig',
    'staff.teachersubjects.apps.TeachersubjectsConfig',

    'exams.apps.ExamsConfig',
    'exams.registration.apps.RegistrationConfig',
    'exams.examtype.apps.ExamtypeConfig',
    'setups.academics.gradingsystem.apps.GradingsystemConfig',

    'useradmin.apps.UseradminConfig',
    'useradmin.users.apps.UsersConfig',
    'usertype.usertype.apps.UsertypeConfig',
    'login.apps.LoginConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
SESSION_EXPIRE_SECONDS = 300
SESSION_TIMEOUT_REDIRECT = '/login/loginpage'

ROOT_URLCONF = 'schoolsys.urls'
LOGIN_URL= '/login/loginpage'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'schoolsys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'TestSchool',
        'USER': 'admin',
        'PASSWORD': 'P4$$W0RD',
        'HOST': 'DESKTOP-1FPK0DH\MSSQLSERVER01',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
}



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'jkkimotho$admindb',
#         'USER': 'jkkimotho',
#         'PASSWORD': 'Gwathimura123',
#         'HOST': 'jkkimotho.mysql.pythonanywhere-services.com',
#         'PORT': '3306',
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'admindb',
#         'USER': 'root',
#         'PASSWORD': 'admin1234',
#         'HOST': '35.239.215.4',
#         'PORT': '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'users.User'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
STATIC_ROOT = os.path.join(BASE_DIR,'assets');

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
