# Generated by Django 3.0 on 2021-11-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastersetups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mastersetups',
            table='Master_Setups',
        ),
    ]
