# Generated by Django 3.0 on 2021-11-02 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastersetups', '0002_auto_20211102_0600'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mastersetups',
            table='Setups_MasterSetups',
        ),
    ]
