# Generated by Django 3.0 on 2021-11-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountmaster', '0009_auto_20211117_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('acm_code', models.AutoField(primary_key=True, serialize=False)),
                ('acm_type', models.CharField(max_length=100)),
                ('acm_desc', models.CharField(max_length=100)),
                ('acm_created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('acm_created_on', models.DateTimeField(blank=True, null=True)),
                ('acm_AccountMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acm_AccountMaster', to='accountmaster.AccountMaster')),
                ('acm_contra_AccountMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acm_contra_AccountMaster', to='accountmaster.AccountMaster')),
            ],
            options={
                'db_table': 'account_mapping',
            },
        ),
    ]
