# Generated by Django 3.0 on 2021-10-29 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20211027_0456'),
        ('gradesgrid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradesgrid',
            name='grades_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Departments'),
        ),
        migrations.AlterField(
            model_name='gradesgrid',
            name='grades_option',
            field=models.CharField(blank=True, default='ALL', max_length=50, null=True),
        ),
    ]
