# Generated by Django 3.0 on 2021-12-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20211027_0456'),
        ('gradesgrid', '0002_auto_20211029_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradesgrid',
            name='grades_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.SchoolDepartments'),
        ),
    ]
