# Generated by Django 3.0 on 2021-10-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCampuses',
            fields=[
                ('campus_code', models.AutoField(primary_key=True, serialize=False)),
                ('campus_name', models.CharField(max_length=10)),
                ('campus_location', models.CharField(max_length=200)),
                ('campus_incharge', models.IntegerField(default=0)),
                ('campus_incharge_contacts', models.CharField(max_length=10)),
                ('campus_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Counties')),
            ],
        ),
    ]
