# Generated by Django 3.0 on 2021-11-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campuses',
            old_name='campus_inchargephone',
            new_name='campus_incharge_contacts',
        ),
    ]
