# Generated by Django 3.0 on 2021-11-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0007_auto_20211118_1007'),
        ('classes', '0002_auto_20211025_0916'),
        ('subjects', '0003_auto_20211027_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjects',
            fields=[
                ('stud_subject_code', models.AutoField(primary_key=True, serialize=False)),
                ('stud_subject_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.SchoolClasses')),
                ('stud_subject_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Students')),
                ('stud_subject_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.SchoolSubjects')),
            ],
        ),
    ]
