# Generated by Django 3.0 on 2021-10-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDepartments',
            fields=[
                ('dp_code', models.AutoField(primary_key=True, serialize=False)),
                ('dp_sht_name', models.CharField(max_length=20)),
                ('dp_name', models.CharField(max_length=200)),
                ('dp_sequence', models.CharField(max_length=20)),
            ],
        ),
    ]
