# Generated by Django 3.0 on 2021-11-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastersetups', '0003_auto_20211102_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersetups',
            name='ms_type',
            field=models.CharField(max_length=100),
        ),
    ]
