# Generated by Django 3.0 on 2021-11-15 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_groups',
            fields=[
                ('ag_code', models.AutoField(primary_key=True, serialize=False)),
                ('ag_prefix', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'account_groups',
            },
        ),
        migrations.CreateModel(
            name='account_main',
            fields=[
                ('ama_code', models.AutoField(primary_key=True, serialize=False)),
                ('ama_desc', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'account_main',
            },
        ),
        migrations.CreateModel(
            name='account_types',
            fields=[
                ('ac_code', models.AutoField(primary_key=True, serialize=False)),
                ('ac_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'account_types',
            },
        ),
        migrations.CreateModel(
            name='account_master',
            fields=[
                ('am_code', models.AutoField(primary_key=True, serialize=False)),
                ('am_desc', models.CharField(max_length=200)),
                ('am_status', models.CharField(max_length=10)),
                ('am_account_no', models.CharField(max_length=50)),
                ('am_cb', models.BooleanField(default=False)),
                ('am_ie', models.BooleanField(default=False)),
                ('am_bs', models.BooleanField(default=False)),
                ('am_pl', models.BooleanField(default=False)),
                ('am_pc', models.BooleanField(default=False)),
                ('am_order', models.IntegerField(default=0)),
                ('am_created_by', models.CharField(max_length=200)),
                ('am_created_on', models.DateField()),
                ('am_account_groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountmaster.account_groups')),
                ('am_account_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountmaster.account_main')),
            ],
            options={
                'db_table': 'account_master',
            },
        ),
        migrations.AddField(
            model_name='account_groups',
            name='ag_accounttypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountmaster.account_types'),
        ),
    ]
