# Generated by Django 3.0 on 2021-11-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_main',
            name='ama_desc',
            field=models.CharField(max_length=100),
        ),
    ]
