# Generated by Django 3.0 on 2021-11-15 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountmaster', '0002_auto_20211115_0600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_groups',
            new_name='AccountGroups',
        ),
        migrations.RenameModel(
            old_name='account_main',
            new_name='AccountMain',
        ),
        migrations.RenameModel(
            old_name='account_master',
            new_name='AccountMaster',
        ),
        migrations.RenameModel(
            old_name='account_types',
            new_name='AccountTypes',
        ),
        migrations.RenameField(
            model_name='accountgroups',
            old_name='ag_accounttypes',
            new_name='ag_AccountTypes',
        ),
        migrations.RenameField(
            model_name='accountmaster',
            old_name='am_account_groups',
            new_name='am_AccountGroups',
        ),
        migrations.RenameField(
            model_name='accountmaster',
            old_name='am_account_main',
            new_name='am_AccountMain',
        ),
    ]
