# Generated by Django 3.0 on 2021-11-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountmaster', '0003_auto_20211115_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmaster',
            name='am_ie',
        ),
    ]
