# Generated by Django 3.0 on 2021-11-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmaster', '0005_accountgroups_ag_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmaster',
            name='am_created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accountmaster',
            name='am_created_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
