# Generated by Django 3.0 on 2021-11-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmaster', '0006_auto_20211116_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmaster',
            name='am_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountmaster',
            name='am_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
