# Generated by Django 3.0 on 2021-11-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmaster', '0008_auto_20211117_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmaster',
            name='am_created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
