# Generated by Django 3.0 on 2021-10-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dorms',
            new_name='SchoolDorms',
        ),
    ]
