# Generated by Django 3.0 on 2021-10-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0002_auto_20211026_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldorms',
            name='current_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
