# Generated by Django 3.0 on 2021-10-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_auto_20211027_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubjects',
            fields=[
                ('subject_code', models.AutoField(primary_key=True, serialize=False)),
                ('subject_sht_Code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_order', models.IntegerField(default=0)),
                ('subject_full', models.BooleanField(default=True)),
                ('subject_main', models.BooleanField(default=True)),
                ('subject_pct', models.IntegerField(default=0)),
                ('subject_comb_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subject_level', models.IntegerField(default=0)),
                ('subject_multiply_by', models.IntegerField(default=0)),
                ('subject_include_for_pos', models.BooleanField(default=True)),
                ('subject_combined', models.BooleanField(default=False)),
                ('subject_gradable', models.BooleanField(default=True)),
                ('subject_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.SchoolDepartments')),
            ],
        ),
    ]
