# Generated by Django 3.0 on 2021-10-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='subject_sht_desc',
            new_name='subject_sht_desc',
        ),
    ]
