# Generated by Django 3.0 on 2021-11-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('org_code', models.AutoField(primary_key=True, serialize=False)),
                ('Org_Name', models.CharField(max_length=100)),
                ('Org_Physical_Address', models.CharField(max_length=200)),
                ('Org_Tel_No', models.CharField(max_length=30)),
                ('Org_Logo', models.ImageField(blank=True, null=True, upload_to='org_logo')),
                ('Org_Email', models.CharField(max_length=100)),
                ('Org_Tag_Line', models.CharField(max_length=200)),
                ('Org_Poastal_Address', models.CharField(max_length=200)),
                ('Org_Type', models.CharField(default=1, max_length=200)),
                ('Org_Logo2', models.ImageField(blank=True, null=True, upload_to='org_logo2')),
                ('Org_Cell_No', models.CharField(max_length=30)),
                ('Org_Mission', models.CharField(blank=True, max_length=200, null=True)),
                ('Org_Vision', models.CharField(blank=True, max_length=200, null=True)),
                ('Org_Pin_No', models.CharField(blank=True, max_length=11, null=True)),
                ('Org_NHIF_Code', models.CharField(blank=True, max_length=30, null=True)),
                ('Org_NSSF_Code', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Setups_Organisation',
            },
        ),
    ]
