# Generated by Django 3.0 on 2021-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='Org_Website',
            field=models.CharField(default='www', max_length=100),
            preserve_default=False,
        ),
    ]
