# Generated by Django 3.0 on 2021-11-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20211109_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='Org_NSSF_Code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='Org_Type',
            field=models.CharField(blank=True, default=1, max_length=200, null=True),
        ),
    ]
