# Generated by Django 3.0 on 2021-11-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20211109_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='Org_Logo2',
            field=models.ImageField(blank=True, null=True, upload_to='Org_Logo2'),
        ),
    ]
