# Generated by Django 3.0 on 2021-11-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20211118_0612'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table=None,
        ),
    ]
