# Generated by Django 3.0 on 2021-11-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20211118_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=200, null=True),
        ),
    ]
