# Generated by Django 3.0 on 2021-12-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20211126_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_resume_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='student_school_status',
            field=models.CharField(blank=True, default='Active', max_length=200),
        ),
        migrations.AddField(
            model_name='students',
            name='student_statuschange_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='student_statuschange_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='student_statuschange_term',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='year_of_completion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
