# Generated by Django 3.0 on 2021-10-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcampuses',
            name='campus_incharge',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='schoolcampuses',
            name='campus_incharge_contacts',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolcampuses',
            name='campus_name',
            field=models.CharField(max_length=100),
        ),
    ]
