# Generated by Django 3.0 on 2021-10-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_auto_20211027_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradesGrid',
            fields=[
                ('grades_code', models.AutoField(primary_key=True, serialize=False)),
                ('grades_val1', models.IntegerField(default=0)),
                ('grades_val2', models.IntegerField(default=0)),
                ('grades_grade', models.CharField(max_length=20)),
                ('grades_remarks', models.CharField(max_length=50)),
                ('grades_option', models.CharField(max_length=50)),
                ('grades_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.SchoolDepartments')),
            ],
        ),
    ]
