# Generated by Django 3.0 on 2021-11-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('param_code', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=50)),
                ('param_value', models.CharField(max_length=200)),
                ('param_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
