# Generated by Django 3.0 on 2021-11-05 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parameters',
            table='Setups_Parameters',
        ),
    ]
